"""add_ingredienten_to_recipes

Revision ID: c5134693b6b0
Revises: 004
Create Date: 2026-05-18 20:08:35.108041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5134693b6b0'
down_revision: Union[str, None] = 'd4e5f6a1b203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification_settings', 'daily_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('notification_settings', 'daily_hour',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('7'))
    op.alter_column('notification_settings', 'daily_minute',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.alter_column('notification_settings', 'shopping_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('notification_settings', 'shopping_days',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'woensdag,zaterdag'::character varying"))
    op.alter_column('notification_settings', 'shopping_hour',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('8'))
    op.alter_column('notification_settings', 'shopping_minute',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('recipes', sa.Column('ingredienten', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'ingredienten')
    op.alter_column('notification_settings', 'shopping_minute',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('notification_settings', 'shopping_hour',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('8'))
    op.alter_column('notification_settings', 'shopping_days',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'woensdag,zaterdag'::character varying"))
    op.alter_column('notification_settings', 'shopping_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('notification_settings', 'daily_minute',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('notification_settings', 'daily_hour',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('7'))
    op.alter_column('notification_settings', 'daily_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
